# Generated by Django 4.1.3 on 2022-12-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=30, unique=True)),
                ('image_url', models.CharField(default='', max_length=300)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=60)),
                ('is_piece', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(default='', max_length=255)),
                ('client_phone', models.CharField(default='', max_length=20)),
                ('reservation_date', models.CharField(default='', max_length=50)),
                ('reservation_time', models.CharField(default='', max_length=30)),
                ('car_year', models.CharField(default='', max_length=30)),
                ('car_engine', models.CharField(default='', max_length=30)),
                ('car_brand', models.CharField(default='', max_length=30)),
                ('car_model', models.CharField(default='', max_length=30)),
                ('engine_type', models.CharField(default='', max_length=30)),
                ('reservation_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.service')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=30)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.service')),
            ],
        ),
    ]
