# Generated by Django 4.1.3 on 2022-11-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
