# Generated by Django 4.1.3 on 2022-12-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_model',
            new_name='car',
        ),
    ]
