# Generated by Django 4.1.3 on 2022-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_car_model_carmodel_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
