# Generated by Django 4.1.3 on 2022-11-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_brand_alter_carmodel_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
