# Generated by Django 4.1.3 on 2022-11-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
