# Generated by Django 4.1.3 on 2022-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_service_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_engine',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_year',
            field=models.CharField(default='', max_length=30),
        ),
    ]
