# Generated by Django 4.1.3 on 2022-12-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_reservation_reservation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
