# Generated by Django 4.1.3 on 2022-11-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_reservation_car_engine_reservation_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel'),
        ),
    ]
