# Generated by Django 4.1.3 on 2022-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_reservation_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.CharField(default='', max_length=30),
        ),
    ]
