# Generated by Django 4.1.3 on 2022-12-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_piece_price_alter_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='workforce_price',
            field=models.IntegerField(default=0),
        ),
    ]
