# Generated by Django 4.1.3 on 2022-12-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_piece_workforce_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
