# Generated by Django 4.1.3 on 2022-12-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_piece_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_pieces',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_piece',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='miniservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.service'),
        ),
    ]
